# Generated by Django 5.2.11 on 2026-02-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_avatar_user_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(help_text="Укажите имя", max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(help_text="Укажите фамилию", max_length=150, verbose_name="Фамилия"),
        ),
    ]
