# Generated by Django 5.2.11 on 2026-02-19 11:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Один вариант"),
                            ("multiple", "Несколько вариантов"),
                            ("text", "Текстовый ответ"),
                        ],
                        default="single",
                        help_text="Выберите тип вопроса",
                        max_length=20,
                        verbose_name="Тип вопроса",
                    ),
                ),
                ("text", models.TextField(help_text="Введите текст вопроса", verbose_name="Текст вопроса")),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Количество баллов за правильный ответ",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Баллы",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Порядковый номер вопроса", verbose_name="Порядок"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Пояснение к правильному ответу", null=True, verbose_name="Пояснение"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "text",
                    models.CharField(help_text="Введите текст ответа", max_length=500, verbose_name="Текст ответа"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, help_text="Отметьте, если это правильный ответ", verbose_name="Правильный ответ"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="tests.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответов",
                "db_table": "answers",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название теста", max_length=200, verbose_name="Название теста"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание теста", null=True, verbose_name="Описание теста"
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Укажите время на прохождение теста в минутах",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Лимит времени (минуты)",
                    ),
                ),
                (
                    "attempts_allowed",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Укажите количество допустимых попыток",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество попыток",
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=70,
                        help_text="Укажите минимальный процент для прохождения",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Проходной балл (%)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Отметьте, если тест доступен для прохождения", verbose_name="Активен"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "lesson",
                    models.OneToOneField(
                        help_text="Выберите урок для теста",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test",
                        to="courses.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Владелец теста",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
                "db_table": "tests",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                help_text="Выберите тест",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="tests.test",
                verbose_name="Тест",
            ),
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="Начало прохождения")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Завершение")),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "В процессе"), ("completed", "Завершен"), ("timeout", "Время вышло")],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True, verbose_name="Баллы")),
                ("percentage", models.FloatField(blank=True, null=True, verbose_name="Процент выполнения")),
                ("passed", models.BooleanField(blank=True, null=True, verbose_name="Тест сдан")),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="tests.test",
                        verbose_name="Тест",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка теста",
                "verbose_name_plural": "Попытки тестов",
                "ordering": ["-started_at"],
                "unique_together": {("test", "user", "status")},
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.PositiveIntegerField(verbose_name="Набрано баллов")),
                ("max_score", models.PositiveIntegerField(verbose_name="Максимальный балл")),
                ("percentage", models.FloatField(verbose_name="Процент выполнения")),
                ("passed", models.BooleanField(verbose_name="Тест сдан")),
                ("completed_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата прохождения")),
                (
                    "attempt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="tests.testattempt",
                        verbose_name="Попытка",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="tests.test",
                        verbose_name="Тест",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат теста",
                "verbose_name_plural": "Результаты тестов",
                "db_table": "test_results",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text_answer", models.TextField(blank=True, null=True, verbose_name="Текстовый ответ")),
                ("is_correct", models.BooleanField(blank=True, null=True, verbose_name="Правильно")),
                ("points_earned", models.FloatField(default=0, verbose_name="Получено баллов")),
                ("answered_at", models.DateTimeField(auto_now_add=True, verbose_name="Время ответа")),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="tests.testattempt",
                        verbose_name="Попытка",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tests.question", verbose_name="Вопрос"
                    ),
                ),
                (
                    "selected_options",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_answers",
                        to="tests.answeroption",
                        verbose_name="Выбранные варианты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ пользователя",
                "verbose_name_plural": "Ответы пользователей",
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
