# Generated by Django 5.2.11 on 2026-02-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswer",
            name="text_answer",
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("single", "Один вариант"), ("multiple", "Несколько вариантов")],
                default="single",
                help_text="Выберите тип вопроса",
                max_length=20,
                verbose_name="Тип вопроса",
            ),
        ),
    ]
