# Generated by Django 5.2.11 on 2026-02-20 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_remove_useranswer_text_answer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testattempt",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="testattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "in_progress")), fields=("test", "user"), name="unique_active_attempt"
            ),
        ),
    ]
